[package]
name = "website-frontend-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.2"
dioxus-router = "0.3.0"
dioxus-use-window = "0.7.0"
gloo-timers = "0.2.6"
gloo-file = {version="0.2.3", features = ["futures"]}
gloo-net = "0.3.0"
gloo-utils = {version = "0.1.7"}
web-sys = {version = "0.3.64",features = ["DomTokenList"]}
charming = { version = "0.2.3", features = ["wasm"] }
rand = "0.8.5"
getrandom = { version = "0.2.10", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
aes-wasm = "0.1.6"
