[package]
name = "website-frontend-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.2"
dioxus-router = "0.3.0"
dioxus-use-window = "0.7.0"
reqwest = { version = "0.11", features = ["json"] }
gloo-timers = "0.2.6"
charming = { version = "0.2.3", features = ["wasm"] }
web-sys ={version = "0.3.64", features = ["DomTokenList"]}
rand = "0.8.5"
getrandom = { version = "0.2.10", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"