[package]
name = "rust-exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.2"
dioxus-router = "0.3.0"
dioxus-use-window = "0.7.0"
reqwest = { version = "0.11", features = ["json"] }
gloo-timers = "0.2.6"
